services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}-nginx:latest
    build:
      context: ./.docker/nginx
      args:
        BUILD_ARGUMENT_ENV: staging
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: always
    volumes:
      - ./src:/var/www/html:ro,cached
    depends_on:
      - tarakan_mi
    networks:
      - app
      - nginx-proxy_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

  tarakan_mi:
    image: ${COMPOSE_PROJECT_NAME}-app:latest
    user: "www-data"
    build:
      context: .
      args:
        BUILD_ARGUMENT_ENV: staging
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
      dockerfile: ./.docker/php/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-app
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - sqlserver_db
    networks:
      - app
      - nginx-proxy_network
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3

  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app
    ports:
      - "1433:1433"

networks:
  app:
    name: ${COMPOSE_PROJECT_NAME}_network
  nginx-proxy_network:
    external: true

volumes:
  sqlserver_data:
    name: sqlserver_sqlserver_data
    external: true
